version: '3.8'
name: trocas_do_carro
services:
  db:
    image: postgres:latest
    container_name: trocas_do_carro_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trocas_do_carro
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: